-- RAG knowledge base: pgvector + knowledge_documents / knowledge_chunks + match_chunks.
--
-- Column sets mirror the mobile project's tables (project wrbauxutkysljmsqojts) so its
-- knowledge_documents / knowledge_chunks export copies in 1:1. Embeddings are OpenAI
-- text-embedding-3-small (1536-dim); the rag-query edge function embeds the user's query
-- with the same model and searches these via match_chunks().

create extension if not exists vector with schema extensions;

-- Documents (column order matches the mobile CSV export exactly)
create table if not exists public.knowledge_documents (
  id bigint generated by default as identity primary key,
  title text,
  storage_path text,
  subject text,
  section text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  content_hash text,
  source_url text
);

create unique index if not exists knowledge_documents_source_url_uniq
  on public.knowledge_documents (source_url)
  where source_url is not null;

-- Chunks
create table if not exists public.knowledge_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.knowledge_documents(id) on delete cascade,
  chunk_index int,
  chunk_text text,
  embedding vector(1536),
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists knowledge_chunks_document_id_idx
  on public.knowledge_chunks (document_id);

-- NOTE: intentionally no ivfflat/hnsw index. With ~350 chunks an exact scan gives
-- perfect recall and is instant; an ivfflat(lists=100) index would probe ~1/100 of the
-- vectors and degrade recall. Add a tuned ANN index once the KB grows large.

-- RLS on (web convention). Only the rag-query edge function touches these, via the
-- service-role key, which bypasses RLS. No client role gets direct access.
alter table public.knowledge_documents enable row level security;
alter table public.knowledge_chunks    enable row level security;

-- The blanket ALTER DEFAULT PRIVILEGES in 20260518100800_grants.sql granted
-- authenticated DML on every future public table, so these tables inherited it.
-- Revoke it, and add an explicit deny policy documenting that no client role
-- may read/write directly. service_role bypasses RLS and is granted select
-- below so the edge function still reads the KB. Idempotent (drop-if-exists)
-- so the migration can be safely re-applied.
revoke all on public.knowledge_documents from anon, authenticated;
revoke all on public.knowledge_chunks    from anon, authenticated;

drop policy if exists knowledge_documents_no_client_access on public.knowledge_documents;
create policy knowledge_documents_no_client_access on public.knowledge_documents
  as restrictive for all to anon, authenticated using (false) with check (false);

drop policy if exists knowledge_chunks_no_client_access on public.knowledge_chunks;
create policy knowledge_chunks_no_client_access on public.knowledge_chunks
  as restrictive for all to anon, authenticated using (false) with check (false);

grant select on public.knowledge_documents, public.knowledge_chunks to service_role;

-- Vector search: recency-weighted similarity (85% cosine + 15% recency), returns
-- source_url in the document jsonb (matches the mobile rag-query contract).
create or replace function public.match_chunks(
  query_embedding vector(1536),
  match_threshold float default 0.5,
  match_count int default 5
)
returns table (
  id bigint,
  document_id bigint,
  chunk_index int,
  chunk_text text,
  similarity float,
  knowledge_documents jsonb
)
language plpgsql
stable
set search_path = public, extensions
as $$
-- OUT params (id, document_id, similarity, …) share names with the queried
-- columns; resolve ambiguous references to the column, not the variable.
#variable_conflict use_column
begin
  return query
  with candidate_chunks as (
    select
      kc.id,
      kc.document_id,
      kc.chunk_index,
      kc.chunk_text,
      kc.embedding <=> query_embedding as embedding_distance,
      greatest(
        0,
        1.0 - extract(epoch from (now() - coalesce(kc.updated_at, kc.created_at))) / (180.0 * 86400)
      ) as recency_factor,
      jsonb_build_object(
        'id', kd.id,
        'title', kd.title,
        'storage_path', kd.storage_path,
        'subject', kd.subject,
        'section', kd.section,
        'source_url', kd.source_url,
        'updated_at', kd.updated_at
      ) as knowledge_documents
    from public.knowledge_chunks kc
    join public.knowledge_documents kd on kc.document_id = kd.id
    where kc.embedding is not null
    order by kc.embedding <=> query_embedding
    limit greatest(match_count * 8, 50)
  )
  -- Qualify every output column with the CTE alias: the RETURNS TABLE OUT
  -- params share these names, so an unqualified `id` etc. is ambiguous.
  select
    candidate_chunks.id,
    candidate_chunks.document_id,
    candidate_chunks.chunk_index,
    candidate_chunks.chunk_text,
    ((1 - candidate_chunks.embedding_distance) * 0.85
      + candidate_chunks.recency_factor * 0.15)::float as similarity,
    candidate_chunks.knowledge_documents
  from candidate_chunks
  where match_threshold <= 0
    or 1 - candidate_chunks.embedding_distance > match_threshold
  order by similarity desc
  limit match_count;
end;
$$;
